site_name: NOAA Omics Technical Portal
theme:
  name: readthedocs
  highlightjs: true
extra_css: [style_2.css]
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Home: 'index.md'
  - 'Data Management and Standards': 'data-management.md'
  - 'Omics Protocols': 'omics-protocols.md'
  - 'Bioinformatics Sequence Processing Protocols': 'bioinformatics-protocols.md'
  - 'Aggregated Relevant NOAA Line Office GitHub Repositories': 'noaa-repos.md'
  - 'Training Resources': 'training.md'
  - 'Missing NOAA GitHub Repositories?': 'missing.md'
  - 'Contributors': 'contributors.md'
  - 'Omics Glossary': 'glossary.md'
  - 'Discussion Forum (external)': "https://github.com/orgs/NOAA-Omics/discussions"
use_directory_urls: false
markdown_extensions:
  - toc:
      permalink: "#"
