[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NOAA Omics Technical Portal"
authors = [{name = "NOAA Omics", email = ""}]
dynamic = ["version", "description"]
