[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NOAA-Omics-Technical-Portal"
authors = [{name = "Zack Gold", email = "zachary.gold@noaa.gov"}]
dynamic = ["version", "description"]
